# https://docs.renovatebot.com/user-stories/maintaining-aur-packages-with-renovate/
# Thanks Jamie!

name: aur
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  updpkgsums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          echo "pkgbuild=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV
      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: 'updpkgsums'
          pkgname: ${{ env.pkgbuild }}
      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO'
